version: "3"

services:

  fireflyiii:
    image: fireflyiii/core:latest
    container_name: fireflyiii
    environment:
      - APP_KEY=${FIREFLYIII_APP_KEY}
      - APP_URL=https://firefly-iii.home.arpa
      - DB_CONNECTION=sqlite
      - TRUSTED_PROXIES=**
      - VIRTUAL_HOST=firefly-iii.home.arpa
      - VIRTUAL_PORT=8080
    restart: unless-stopped
    volumes:
      - fireflyiii_database_data:/var/www/html/storage/database
      - fireflyiii_upload_data:/var/www/html/storage/upload

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    environment:
      - NETWORK_ACCESS=internal
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./.docker/nginx-proxy/vhost.d/:/etc/nginx/vhost.d/:ro
      - ./.docker/nginx-proxy/certs/:/etc/nginx/certs/:ro

  pihole:
    image: pihole/pihole:2022.07.1
    container_name: pihole
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=pihole.home.arpa
      - WEBPASSWORD=${PIHOLE_WEB_PASSWORD}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    volumes:
      - pihole_dnsmasq_data:/etc/dnsmasq.d
      - pihole_etc_data:/etc/pihole

  portainer:
    image: portainer/portainer-ce:2.14.2-alpine
    container_name: portainer
    environment:
      - VIRTUAL_HOST=portainer.home.arpa
      - VIRTUAL_PORT=9443
      - VIRTUAL_PROTO=https
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data/

  # todo: configure SMTP-server: https://github.com/dani-garcia/vaultwarden/blob/a30a1c970365f78d45c123a04f8288ced7cd3390/.env.template#L327-L338
  vaultwarden:
    image: vaultwarden/server:1.25.2-alpine
    container_name: vaultwarden
    environment:
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - DOMAIN=https://vaultwarden.home.arpa
      - SIGNUPS_ALLOWED=false
      - VIRTUAL_HOST=vaultwarden.home.arpa
      - WEBSOCKET_ENABLED=true
    restart: unless-stopped
    volumes:
      - vaultwarden_data:/data/

volumes:
  fireflyiii_database_data:
  fireflyiii_upload_data:
  pihole_etc_data:
  pihole_dnsmasq_data:
  portainer_data:
  vaultwarden_data:
