version: "3.9"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - VIRTUAL_HOST=portainer.home.arpa
      - VIRTUAL_PORT=9443
      - VIRTUAL_PROTO=https
    restart: always
    volumes:
      - portainer_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  portainer_data:
